### ISSUE TITLE
좋아요 처리에 대한 로직 오류

### ISSUE THREAD

**Issue by Johnjihwan** [theMomentTeam/the_moment-Client#86]
<img width="258" alt="Screen Shot 2021-05-20 at 3 58 52 PM" src="https://user-images.githubusercontent.com/67095821/118933547-4aff5080-b984-11eb-9562-d943fd160213.png">

Error을 유발하는 Action 순서
> 1. 좋아요를 누른다
> 2. 새로고침
> 3. 그 게시물 좋아요를 다시 누르면, -1 로 보여집니다.

**사용자로 하여금 치명적인 오류로 보입니다. 조속한 처리 부탁드립니다!**

**Comment by Goolgae** [comment]
확인했습니다

**Comment by Goolgae** [comment]
이미 해결한 이슈이지만, release 브랜치에 pr이 들어가지 않아서 배포에는 해당되지 않은것 같습니다.
